import { headers } from "next/headers";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";
import ClientProviders from "@/components/ClientProvider";
import Center from "@/components/Center";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const heads = headers();
  const pathname = heads.get("next-url");

  return (
    <ClientProviders>
      <html lang="en">
        <body className={inter.className}>
          <main className="flex">
            {pathname !== "/login" && <Sidebar />}
            <div className="h-screen overflow-y-scroll flex-1 bg-black">
              {children}
            </div>
          </main>
        </body>
      </html>
    </ClientProviders>
  );
}
